server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        show_sql: true
  h2:
    console:
      enabled: true
  datasource:
    url:  jdbc:h2:mem:testdb
    username: sa
    password:



jwt:
  secret-key : okr-project-application-2022-11-29.secret-key
  token:
    refresh-expired-time-ms : 259200000
    access-expired-time-ms : 259200000

google:
    clientId: 30536199705-2sg1uhnfad1png6biv8clh22gtd5i006.apps.googleusercontent.com